### ISSUE TITLE
stdint.h: No such file or directory

### ISSUE THREAD

**Issue by AnirudhPal** [sandeepmistry/arduino-nRF5#103] opened 2017-02-25 09:21 UTC
Using this library 0.2.0
Board: nRF52 DK
OS: Windows 10
Arduino Ver: 1.8.1
Description:
1. Followed the instructions as stated in the README.
2. Device Manager sees the nRF52 as JLINK deivce.
3. When I attempt to upload the 'Blink' sketch, it throws an error.
Error: Line 9 of stdint.h: No such file or directory

**Comment by dlabun** [comment] 2017-02-25 12:32
We have seen this issue before with corrupt installations, please try deleting the core and reinstalling it. Unpacking the core does take some time, over 10 minutes is possible.

**Comment by sandeepmistry** [comment] 2017-02-25 14:06
@dlabun thanks for helping out!

I'm closing this as duplicate of #57 for now, until we have more info.

**Closed by sandeepmistry** 2017-02-25 14:06 UTC
