### ISSUE TITLE
Support for ble mesh using nrf52 

### ISSUE THREAD

**Issue by Nakul93** [sandeepmistry/arduino-nRF5#275] opened 2018-05-20 07:47 UTC
Is there mesh examples for nrf52 in arduino...if not then when will it be available?

**Comment by probonopd** [comment] 2018-05-20 09:50
Duplicate of https://github.com/sandeepmistry/arduino-nRF5/issues/62

**Comment by dlabun** [comment] 2018-05-20 10:56
As listed in the readme: This Arduino Core does not contain any Arduino style API's for BLE functionality

**Closed by dlabun** 2018-05-20 10:56 UTC

**Comment by probonopd** [comment] 2018-05-20 23:38
...but its sister project, https://github.com/sandeepmistry/arduino-BLEPeripheral does :-) maybe ask there.
