### ISSUE TITLE
unable to flash softdevice: nordic's softdevice download url changed

### ISSUE THREAD

**Issue by Pathak94** [sandeepmistry/arduino-nRF5#332] opened 2019-01-14 10:44 UTC
Inside softdevices.txt file the url for downloading softdevice has changed. 
But I was still able to make it work by manually installing same softdevice and pasting the file inside "sandeepmistry/nRF5/cores/nRF5/SDK/components/softdevice/s132/hex/" .

**Comment by dlabun** [comment] 2019-01-14 11:03
Duplicate of #312

**Closed by dlabun** 2019-01-14 11:03 UTC
