### ISSUE TITLE
Fix dead links in README

### ISSUE THREAD

**Issue by E3V3A** [sandeepmistry/arduino-nRF5#346] opened 2019-02-22 00:12 UTC
Please update all the dead links in the README. 
(In particular those to Nordic Sem)

**Comment by dlabun** [comment] 2019-02-22 01:08
Duplicate of issues listed in #312

**Closed by dlabun** 2019-02-22 01:08 UTC
Labels: duplicate

**Comment by E3V3A** [comment] 2019-02-22 09:29
@dlabun 
I wouldn't call that a duplicate, totally different issues and title.

I suggest to not link directly to the file themselves, but to the pages where the user can easily understand what files to download. If not, then perhaps just download yourself and add to this repo (unless they are huge). Kind of what the last commenter did in that issue.
