### ISSUE TITLE
digitalRead since it always returns LOW despite digitalWrite was called with HIGH value.

### ISSUE THREAD

**Issue by Navis-Raven** [sandeepmistry/arduino-nRF5#308] opened 2018-08-31 08:12 UTC
There is a notable bug with nRF52-DK with arduino framwork, as you can see on github here (see the point 7), click on this link : https://github.com/platformio/platformio-docs/issues/33#issuecomment-416382889

The problematic code is here: https://docs.platformio.org/en/latest/tutorials/nordicnrf52/arduino_debugging_unit_testing.html#writing-unit-tests

![image](https://user-images.githubusercontent.com/15887222/44900962-6161ab80-ad06-11e8-87d7-cfa59e73f8d6.png)

there is a problem with function digitalRead since it always returns LOW despite the fact that digitalWrite was called with HIGH value.

The issue is also declared in Nordic, where there is more information: https://devzone.nordicsemi.com/f/nordic-q-a/38028/there-is-a-notable-bug-in-nrf52-dk-with-arduino-framework

IDE: VSCODE with platformio,
SDK/Framwork: Arduino

**Comment by dlabun** [comment] 2018-08-31 10:55
Can you reproduce this issue in the Arudino IDE? This project is intended only for use with the Arduino IDE.

**Comment by Navis-Raven** [comment] 2018-08-31 11:50
I don't have UNITY (unit testing) in my arduino IDE...
Anyway this bug is independant from the IDE: platformIO uses arduino console commands to build project (the same as arduino IDE)

**Comment by Navis-Raven** [comment] 2018-08-31 11:53
If you have time, try to run a test with your nRF52-DK 

By reading after writing HIGH, and print this into your serial debug.

**Comment by dlabun** [comment] 2018-08-31 12:35
Unfortunately this will have to wait until I have time to dig into that part of the project.

**Comment by Navis-Raven** [comment] 2018-08-31 20:55
@sandeepmistry it's a bug, not a "help wanted" post.

**Comment by dlabun** [comment] 2018-08-31 21:38
It's nothing more than a flag indicating that help from others to locate and correct the issue would be appreciated. If you would prefer that we remove the help wanted flag I can certainly do that.

**Comment by Navis-Raven** [comment] 2018-08-31 21:39
Ok, I didn't understand this like that.

**Comment by jandrassy** [comment] 2018-09-03 17:30
why should digitalRead on an OUTPUT pin return something meaningful? or digitalWrite write something to an INPUT pin?

**Comment by Navis-Raven** [comment] 2018-09-03 17:37
@jandrassy I don't know but the platformIO website referenced it as an issue of the arduino framework. 

![image](https://user-images.githubusercontent.com/15887222/44997712-a872c980-afb0-11e8-9407-19776665d9a7.png)

**Comment by jandrassy** [comment] 2018-09-03 17:56
https://arduino.stackexchange.com/questions/13588/read-output-pin-value-in-arduino-due

**Comment by Navis-Raven** [comment] 2018-09-03 18:09
@jandrassy  so in your opinion it's the PlatformIO documentation which is incorrect, isn't it ?

**Comment by valeros** [comment] 2018-09-03 18:26
Hi everyone! I'm not a specialist in the Arduino framework, but I thought it's reasonable to expect that `digitalRead` should return the current state of the pin? Anyway. I've just tested the following code with Uno board in Arduino IDE and it works like I expected:
```
void setup()
{
  Serial.begin(9600);
  pinMode(LED_BUILTIN, OUTPUT);
}
void loop()
{
  digitalWrite(LED_BUILTIN, HIGH);
  Serial.print("Pin value after HIGH: ");
  Serial.println(digitalRead(LED_BUILTIN));
  delay(1000);
  digitalWrite(LED_BUILTIN, LOW);
  Serial.print("Pin value after low: ");
  Serial.println(digitalRead(LED_BUILTIN));
  delay(1000);
}
```
And here is the output:
```

**Comment by dlabun** [comment] 2018-09-03 20:47
It looks like this is expected behavior as it's been reported with all of the official Arduino boards using ARM processors. It's noted in multiple places that the AVRs (and specifically the Uno) are able to read the output simply because of the way their registers are designed. Since this project is correctly reflecting the same behavior as the official Arduino Zero and Due cores I am going to say this is purely a documentation issue on PlatformIO's side.

**Comment by Navis-Raven** [comment] 2018-09-03 23:54
@valeros 
This is what @jandrassy was pointing
![image](https://user-images.githubusercontent.com/15887222/45003692-6912a000-afe5-11e8-8a57-f7fd8dd6cde3.png)

**Comment by dlabun** [comment] 2018-09-05 23:45
I’m closing this as not an issue with project but rather the PlatformIO documentation.

**Closed by dlabun** 2018-09-05 23:45 UTC
Labels: invalid
